//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarTrack.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminUserInfo
    {
        public int SKey { get; set; }
        public string UserID { get; set; }
        public string UserPassword { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public string UserType { get; set; }
    }
}
