//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarTrack.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class APILog
    {
        public int RequestID { get; set; }
        public System.DateTime RequestDate { get; set; }
        public System.DateTime ResponseDate { get; set; }
        public Nullable<int> TimeTaken { get; set; }
        public Nullable<int> APICode { get; set; }
        public Nullable<bool> ErrorFound { get; set; }
        public string ErrorCode { get; set; }
        public string APIResponse { get; set; }
        public string UserID { get; set; }
        public string IPAddress { get; set; }
        public string Source { get; set; }
        public string UserDeviceID { get; set; }
    }
}
