//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarTrack.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarTrackEntities : DbContext
    {
        public CarTrackEntities()
            : base("name=CarTrackEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<APILog> APILogs { get; set; }
        public DbSet<APIMaster> APIMasters { get; set; }
        public DbSet<DefaultSetting> DefaultSettings { get; set; }
        public DbSet<DeviceInventory> DeviceInventories { get; set; }
        public DbSet<EmailTemplate> EmailTemplates { get; set; }
        public DbSet<ErrorMessageMaster> ErrorMessageMasters { get; set; }
        public DbSet<Feedback> Feedbacks { get; set; }
        public DbSet<MyCar> MyCars { get; set; }
        public DbSet<OneTimePassword> OneTimePasswords { get; set; }
        public DbSet<UserInformation> UserInformations { get; set; }
        public DbSet<UserSetting> UserSettings { get; set; }
        public DbSet<AdminUserInfo> AdminUserInfoes { get; set; }
    }
}
