//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarTrack.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceInventory
    {
        public string BeaconID { get; set; }
        public bool InventoryStatus { get; set; }
        public System.DateTime InventoryIncDate { get; set; }
        public Nullable<bool> IsRegistered { get; set; }
        public string EmailAddress { get; set; }
        public string BeaconUDID { get; set; }
        public Nullable<int> Major { get; set; }
        public Nullable<int> Minor { get; set; }
        public string ProximityUDID { get; set; }
        public string Color { get; set; }
    }
}
