//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarTrack.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public string UserID { get; set; }
        public string UserFeedback { get; set; }
        public System.DateTime FeedbackDate { get; set; }
        public int Rating { get; set; }
        public string RatingText { get; set; }
        public int FeedBackID { get; set; }
    
        public virtual UserInformation UserInformation { get; set; }
    }
}
