//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarTrack.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInformation
    {
        public UserInformation()
        {
            this.Feedbacks = new HashSet<Feedback>();
            this.MyCars = new HashSet<MyCar>();
        }
    
        public string UserID { get; set; }
        public string UserPassword { get; set; }
        public string EmailAddress { get; set; }
        public string MobileNumber { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<int> LoginErrorCount { get; set; }
        public Nullable<bool> IsLocked { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public string IPAddress { get; set; }
        public string UserDeviceID { get; set; }
        public string AuthToken { get; set; }
    
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        public virtual ICollection<MyCar> MyCars { get; set; }
        public virtual OneTimePassword OneTimePassword { get; set; }
        public virtual UserSetting UserSetting { get; set; }
    }
}
