//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarTrack.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSetting
    {
        public string UserID { get; set; }
        public int NotificationInterval { get; set; }
        public string NotificationLanguage { get; set; }
    
        public virtual UserInformation UserInformation { get; set; }
    }
}
