//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarTrackAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyCar
    {
        public string UserID { get; set; }
        public string BeaconID { get; set; }
        public string CarName { get; set; }
        public Nullable<bool> IsFavorite { get; set; }
        public byte[] BecaonImage { get; set; }
    }
}
