//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarTrackAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInformation
    {
        public string UserID { get; set; }
        public string UserPassword { get; set; }
        public string EmailAddress { get; set; }
        public string MobileNumber { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<int> LoginErrorCount { get; set; }
        public Nullable<bool> IsLocked { get; set; }
    }
}
